blogapp/urls.py
from django.urls import path
from . import views
from .views import BlogList, BlogDetail, TagView, CommentView

app_name = 'blogapp'

urlpatterns = [
    path('', BlogList.as_view(), name='list'),
    path('detail/<int:pk>', BlogDetail.as_view(), name='detail'),
    path('comment/create/<int:pk>/', views.CommentView.as_view(), name='comment_create'),
    path('tag/<str:tag>/', TagView.as_view(),name='tag'),
    path('search/', views.SearchView.as_view(), name='search'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('markdownx/', include('markdownx.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),
]

blogapp/models.py
from django.db import models
from django.db.models.base import Model
from django.utils import timezone
from mdeditor.fields import MDTextField
from markdown import markdown

# Create your models here.

"""タグモデル"""
class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('タグ一覧')
        verbose_name_plural = ('タグ一覧')

CATEGORY = (('Illustration','イラスト'),('life','日常'),('business','仕事関係'))

"""ブログモデル"""
class BlogModel(models.Model):
    title = models.CharField(max_length=100, verbose_name='タイトル')
    content = MDTextField(verbose_name='内容')
    postdate = models.DateField(auto_now_add=True, verbose_name='投稿日')
    category = models.CharField(
        max_length= 50,
        choices= CATEGORY,
        verbose_name= 'ジャンル'
    )
    #Tagモデルと紐づけ
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="タグ")

    #管理サイトに表示されるオブジェクト名を「title」フィールド名に設定
    def __str__(self):
        return self.title

    #MarkDown記法で書かれたtextをHTML形式に変換して返す
    def get_markdown_text_as_html(self):
        return markdown(self.content)

    #メタデータ（付帯情報）を追加
    class Meta:
        verbose_name = ('ブログ記事投稿')
        verbose_name_plural = ('ブログ記事投稿')


"""コメントモデル"""
class Comment(models.Model):
    user_name = models.CharField('名前', max_length=255, default='名無し')
    message = models.TextField('本文')
    target = models.ForeignKey(BlogModel, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', default=timezone.now)
 
    def __str__(self):
        return self.message[:20]

    class Meta:
        verbose_name = ('コメント一覧')
        verbose_name_plural = ('コメント一覧')

"""返信モデル"""
class Reply(models.Model):
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = ('返信')
        verbose_name_plural = ('返信')

blogapp/forms.py
from django import forms
from .models import Comment

"""コメント投稿フォーム"""
class CommentCreateForm(forms.ModelForm):
    """コメントフォーム"""
    class Meta:
        model = Comment
        exclude = ('target', 'created_at')

class PostForm(forms.Form):
    title = forms.CharField(max_length=30, label='タイトル')
    content = forms.CharField(label='内容', widget=forms.Textarea())

blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.http import HttpResponseRedirect, request
from .models import BlogModel, Tag, Comment
from .forms import CommentCreateForm
from django.urls import reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.views import generic
from django import forms
from django.core.checks import messages
from django.contrib import messages
from django.db.models import Q
from functools import reduce
from operator import and_

'''ブログ一覧'''
class BlogList(ListView):
    template_name = 'list.html'
    model = BlogModel
    paginate_by = 10

    # クエリを実行してレコードを抽出（投稿日付【降順】に並べ替え）
    def get_queryset(self):
        posts = BlogModel.objects.order_by('-postdate')
        return posts


'''ブログ詳細'''
class BlogDetail(DetailView):
    template_name = 'detail.html'
    model = BlogModel


'''ブログ作成'''
class BlogCreate(CreateView):
    template_name = 'create.html'
    model = BlogModel
    fields = ('title', 'content', 'category')
    success_url = reverse_lazy('list')


'''ブログ削除'''
class BlogDelete(DeleteView):
    template_name = 'delete.html'
    model = BlogModel
    success_url = reverse_lazy('list')


'''ブログ更新'''
class BlogUpdate(UpdateView):
    template_name = 'update.html'
    model = BlogModel
    fields = ('title', 'content', 'category')
    success_url = reverse_lazy('list')


class TagDetail(SingleObjectMixin, ListView):
    model = Tag
    paginate_by = 10
    template_name = "tag_detail.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Tag.objects.all())
        return super().get(request, *args, **kwargs)

    # 辞書形式のデータとして取得し、テンプレートにデータベースのデータを出力
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.object
        return context

    # クエリを実行してレコードを抽出（投稿日付【降順】に並べ替え）
    def get_queryset(self):
        return self.object.post_set.all().order_by('-postdate')


"""タグ表示"""
class TagView(generic.ListView):
    model = BlogModel
    template_name = 'list.html'

    def get_queryset(self):
        tag = Tag.objects.get(name=self.kwargs['tag'])
        queryset = BlogModel.objects.order_by('-id').filter(tag=tag)
        messages.success(self.request, '検索完了しました')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_key'] = self.kwargs['tag']
        return context


class CommentView(generic.CreateView):
    template_name = 'comment_form.html'
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(BlogModel, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return redirect('blogapp:detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(BlogModel, pk=self.kwargs['pk'])
        return context

    '''検索機能'''
class SearchView(View):
    def get(self, request, *args, **kwargs):
        post_data = BlogModel.objects.order_by('-postdate')
        keyword = request.GET.get('keyword')

        if keyword:
            exclusion_list = set([' ', '　'])
            query_list = ''
            for word in keyword:
                if not word in exclusion_list:
                    query_list += word
            #Qオブジェクトを使用して、投稿データを検索入力したキーワードでフィルターをかける(or検索)
            query = reduce(and_, [Q(title__icontains=q) | Q(content__icontains=q) for q in query_list])
            post_data = post_data.filter(query)

        return render(request, 'list.html', {
            'keyword' : keyword,
            'post_data' : post_data
        })

blogapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <!--マークダウンのプレビュー表示通りにしたい-->
  <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet">
  <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet">


  <title>yoshida blog</title>
  
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

  {% block header %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogapp:list' %}">Yoshida Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blogapp:list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
        <form class="d-flex" method="get" action="{% url 'blogapp:search' %}">
          <input class="form-control me-2" type="text" name="keyword" placeholder="記事検索">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  {% endblock header %}

  {% block content %}
  {% endblock content %}

  <script src="{% static 'mdeditor/js/jquery.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/editormd.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/marked.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/prettify.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/raphael.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/underscore.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/sequence-diagram.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/flowchart.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/jquery.flowchart.min.js' %}"></script>
  <script>
    $(function () {
      editormd.markdownToHTML("content", {
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true,
      });
      $(".reference-link").each(function (i, obj) {
        console.log(obj)
      })
    })
  </script>


</body>

</html>

blogapp/templates/comment_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'comment_sytle.css' %}">

<div class="container col-lg-6 offset-lg-3">
    <h2 class="titleline"><span>{{ post.title }}</span></h2>
    <form action="" method="POST" id="comment-form">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}

            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <div class="row my-3">
            <button type="submit" class="btn btn-success col-3 offset-2">投稿する</button>
            <a class="btn btn-danger col-3 offset-2" href="{% url 'blogapp:detail' post.pk %}">キャンセル</a>
        </div>
    </form>
</div>

{% endblock content %}

blogapp/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'detail_style.css' %}">

<!--全体-->
<div class="container">

    <!--パンくずリスト-->
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'blogapp:list' %}">List</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detail</li>
        </ol>
    </nav>

    <!--記事-->
    <div class="card text-center">

        <article>

            <div class="card-header">
                {{object.category}}
            </div>

            <div class="card-body">

                <h5 class="card-title"> {{object.title}}</h5><br>
                <div class="card-text" id="content">{{object.content|markdown|safe}}</div>

                <!--<a href="#" class="card-text">#{{object.tags}}</a><br>-->

                <div class="button-menu">
                    <a href="{% url 'blogapp:list' %}" class="btn btn-primary">一覧へ戻る</a>
                    <a href="{% url 'blogapp:comment_create' object.pk %}" class="btn btn-primary">コメントする</a>
                </div>


            </div>

            <section>
                <div class="card-footer text-muted">
                    {{object.postdate}}
                </div>
            </section>

        </article>

    </div>

    <h3 class="comment-title">コメント</h3>

    <!--コメント-->
    {% for comment in object.comment_set.all %}
    <div class="comment-list">
        <div class='border-bottom'>{{ comment.user_name }}　{{ comment.created_at }}</div>

        <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
        <div class='mt-2'>{{ comment.message | linebreaks | urlize }}</div>
    </div>
    {% empty %}
    <p>コメントはありません</p>
    {% endfor %}

</div>

{% endblock content %}

blogapp/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'list_style.css' %}">

<!--全体-->
<div class="container">
  
  <!--タグ一覧-->
  <div class="tag-line">

    <h3>タグ一覧</h3><br>

    {% for tag in tag_list %}
    <a href="{% url 'blogapp:tag' tag %}" class="btn btn-outline-dark">
      <p>{{ tag.name }}</p>
    </a>
    {% endfor %}

  </div>

  <!--タグ検索時のメッセージ表示-->
  {% if messages %}
    {% for message in messages %}
    <p class="message_fontcolor">{{ message }}</p>
    {% endfor %}
  {% endif %}

  <!--検索バーの検索結果メッセージ表示-->
  {% if keyword %}
    <h4 class="mb-4">「{{ keyword }}の検索結果」</h4>
  {% endif %}

  <!--ブログ一覧-->
  {% for item in object_list %}

  <div class="card text-center">

    <div class="card-header">
      {{item.category}}
    </div>

    <div class="card-body">

      <h4 class="card-title"> {{item.title}}</h4>
      <div class="card-text">{{item.content | truncatechars:50}}</div>

      <a href="{% url 'blogapp:detail' item.pk %}" class="btn btn-primary">詳細をみる</a>

    </div>

    <div class="card-footer text-muted">
      {{item.postdate}}
    </div>

  </div>

  {% endfor %}

  <!--プロフィール-->
  <div class="card" style="width: 18rem;">
    <img src="{% static 'usasa.png' %}" class="card-img-top" alt="profile-image">
    <div class="card-body">
      <h5 class="card-title">自己紹介</h5>
      <p class="card-text">吉田と申します。SE＆プログラマーです。<br>ここではプログラミングの話題をメインにブログを綴っていこうと思います。</p>
    </div>
    <ul class="list-group list-group-flush">
      <a href="https://twitter.com/D6CLR9VGT6iYCbX"><li class="list-group-item">Twitter</li></a>
      <a href="https://github.com/Yoshida-Programmer"><li class="list-group-item">Github</li></a>
      <a href="#"><li class="list-group-item">Facebook</li></a>
    </ul>
    
  </div>

  
  

</div>

<!--ページネーション機能-->
<nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo;</span>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item disabled">
      <span class="page-link">{{ i }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock content %}